In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
from mlxtend.data import loadlocal_mnist

In [4]:
X_train, y_train = loadlocal_mnist(
        images_path='./train-images-idx3-ubyte', 
        labels_path='./train-labels-idx1-ubyte')

In [5]:
print('Dimensions: %s x %s' % (X_train.shape[0], X_train.shape[1]))

Dimensions: 18225 x 784


In [6]:
X_test, y_test = loadlocal_mnist(
        images_path='./test-images-idx3-ubyte', 
        labels_path='./test-labels-idx1-ubyte')

In [7]:
print('Dimensions: %s x %s' % (X_test.shape[0], X_test.shape[1]))

Dimensions: 4563 x 784


In [8]:
y_train = tf.keras.utils.to_categorical(y_train) #Converts a class vector (integers) to binary class matrix.
y_test = tf.keras.utils.to_categorical(y_test)

In [9]:
X_train = (X_train-127.5)/127.5
X_test = (X_test-127.5)/127.5


In [13]:

model = tf.keras.models.Sequential([
    
    tf.keras.layers.Flatten(input_shape=(784,)),
    tf.keras.layers.Dense(1024, activation='relu'),
    tf.keras.layers.Dropout(0.25),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dropout(0.25),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dropout(0.25),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.25),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')  
    
])

optimizer = tf.keras.optimizers.Adam(learning_rate=5e-4)
model.compile(optimizer=optimizer, loss='mse', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=20, validation_data=(X_test, y_test))

Train on 18225 samples, validate on 4563 samples
Epoch 1/20
18225/18225 [==============================] - 5s 277us/sample - loss: 0.0329 - accuracy: 0.7545 - val_loss: 0.0094 - val_accuracy: 0.9382
Epoch 2/20
18225/18225 [==============================] - 4s 238us/sample - loss: 0.0158 - accuracy: 0.8985 - val_loss: 0.0070 - val_accuracy: 0.9544
Epoch 3/20
18225/18225 [==============================] - 4s 238us/sample - loss: 0.0131 - accuracy: 0.9174 - val_loss: 0.0063 - val_accuracy: 0.9597
Epoch 4/20
18225/18225 [==============================] - 4s 234us/sample - loss: 0.0118 - accuracy: 0.9265 - val_loss: 0.0054 - val_accuracy: 0.9667
Epoch 5/20
18225/18225 [==============================] - 4s 235us/sample - loss: 0.0103 - accuracy: 0.9340 - val_loss: 0.0056 - val_accuracy: 0.9669
Epoch 6/20
18225/18225 [==============================] - 4s 226us/sample - loss: 0.0095 - accuracy: 0.9399 - val_loss: 0.0062 - val_accuracy: 0.9608
Epoch 7/20
18225/18225 [===========================

In [14]:
import struct
with open('./final-test-images-idx3-ubyte', 'rb') as imgpath:
        magic, num, rows, cols = struct.unpack(">IIII",
                                               imgpath.read(16))
        test_F = np.fromfile(imgpath,
                             dtype=np.uint8).reshape(4563, 784)

In [15]:
print('Dimensions: %s x %s' % (test_F.shape[0], test_F.shape[1]))

Dimensions: 4563 x 784


In [16]:
ans = model.predict(test_F)

In [17]:
print(ans)

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [19]:
import csv
with open('output_mnist_2.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['id', 'class'])
    for i in range(len(ans)):
        #print(i+1,prediction)
        writer.writerow([i+1, ans[i].argmax()])
